#=Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms=#

function fibonacci_to_limit(limit::Int)::Vector{Int}
    prev = 0
    current = 1
    fibonacci_numbers = [prev, current]
    while current + prev < limit
        next_fib = prev + current
        prev = current
        current = next_fib
        push!(fibonacci_numbers, next_fib)
    end
    return fibonacci_numbers
end

fibs_to_limit = fibonacci_to_limit(4000000)
ans = sum(x -> x % 2 == 0 ? x : 0, fibs_to_limit)
@info "The answer is " ans
